### ISSUE TITLE
Meta: High-Level Guild Feature Overview (DRAFT)

### ISSUE THREAD

**Issue by hhenrichsen** [hhenrichsen/school-network-bot#17]
Commands:
- [ ] /category - Category creation and management for server staff members
  - [ ] /category create [name] [description]
  - [ ] /category embed [name] <channel> - create an embed that allows joining channels within this category
  - [ ] /category rename [old] [new]
  - [ ] /category delete [name]
- [ ] /channel - Channel creation within preset categories for server members (or optionally, behind a role
  - [ ] /channel create [category] [number] [description]
  - [ ] /channel 
- [ ] /join [channel] - Join channels that already exist
- [ ] /activity - See stats about a given user's activity
- [ ] /top - See individuals who have contributed the most in a given time range (probably since timestamp/message ID, month, week, and day to start out), optionally given a channel
